/*
 * Natural Voice SDK
 * Natural Voice SDKs are easiest and best supported way for most developers to quickly build and iterate Natural Voice applications that integrate with our services programmatically.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SentimentType;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * TranscriptData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-28T17:14:34.313-07:00")
public class TranscriptData {
  @SerializedName("confidence")
  private Float confidence = null;

  @SerializedName("transcript")
  private String transcript = null;

  @SerializedName("emailAddress")
  private String emailAddress = null;

  @SerializedName("language_code")
  private String languageCode = null;

  @SerializedName("sentimentType")
  private SentimentType sentimentType = null;

  @SerializedName("audioId")
  private String audioId = null;

  @SerializedName("appId")
  private String appId = null;

  @SerializedName("metadataAudio")
  private Object metadataAudio = null;

  @SerializedName("unixTimeCreated")
  private BigDecimal unixTimeCreated = null;

  @SerializedName("audioLink")
  private String audioLink = null;

  public TranscriptData confidence(Float confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Get confidence
   * @return confidence
  **/
  @ApiModelProperty(value = "")
  public Float getConfidence() {
    return confidence;
  }

  public void setConfidence(Float confidence) {
    this.confidence = confidence;
  }

  public TranscriptData transcript(String transcript) {
    this.transcript = transcript;
    return this;
  }

   /**
   * Get transcript
   * @return transcript
  **/
  @ApiModelProperty(value = "")
  public String getTranscript() {
    return transcript;
  }

  public void setTranscript(String transcript) {
    this.transcript = transcript;
  }

  public TranscriptData emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * linked email address if attached (mostly used for salesforce)
   * @return emailAddress
  **/
  @ApiModelProperty(value = "linked email address if attached (mostly used for salesforce)")
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public TranscriptData languageCode(String languageCode) {
    this.languageCode = languageCode;
    return this;
  }

   /**
   * language code from metadata (omitted if metadata is skipped)
   * @return languageCode
  **/
  @ApiModelProperty(value = "language code from metadata (omitted if metadata is skipped)")
  public String getLanguageCode() {
    return languageCode;
  }

  public void setLanguageCode(String languageCode) {
    this.languageCode = languageCode;
  }

  public TranscriptData sentimentType(SentimentType sentimentType) {
    this.sentimentType = sentimentType;
    return this;
  }

   /**
   * Get sentimentType
   * @return sentimentType
  **/
  @ApiModelProperty(value = "")
  public SentimentType getSentimentType() {
    return sentimentType;
  }

  public void setSentimentType(SentimentType sentimentType) {
    this.sentimentType = sentimentType;
  }

  public TranscriptData audioId(String audioId) {
    this.audioId = audioId;
    return this;
  }

   /**
   * Get audioId
   * @return audioId
  **/
  @ApiModelProperty(value = "")
  public String getAudioId() {
    return audioId;
  }

  public void setAudioId(String audioId) {
    this.audioId = audioId;
  }

  public TranscriptData appId(String appId) {
    this.appId = appId;
    return this;
  }

   /**
   * Get appId
   * @return appId
  **/
  @ApiModelProperty(value = "")
  public String getAppId() {
    return appId;
  }

  public void setAppId(String appId) {
    this.appId = appId;
  }

  public TranscriptData metadataAudio(Object metadataAudio) {
    this.metadataAudio = metadataAudio;
    return this;
  }

   /**
   * Get metadataAudio
   * @return metadataAudio
  **/
  @ApiModelProperty(value = "")
  public Object getMetadataAudio() {
    return metadataAudio;
  }

  public void setMetadataAudio(Object metadataAudio) {
    this.metadataAudio = metadataAudio;
  }

  public TranscriptData unixTimeCreated(BigDecimal unixTimeCreated) {
    this.unixTimeCreated = unixTimeCreated;
    return this;
  }

   /**
   * Unix Time (https://en.wikipedia.org/wiki/Unix_time) in nanoseconds
   * @return unixTimeCreated
  **/
  @ApiModelProperty(value = "Unix Time (https://en.wikipedia.org/wiki/Unix_time) in nanoseconds")
  public BigDecimal getUnixTimeCreated() {
    return unixTimeCreated;
  }

  public void setUnixTimeCreated(BigDecimal unixTimeCreated) {
    this.unixTimeCreated = unixTimeCreated;
  }

  public TranscriptData audioLink(String audioLink) {
    this.audioLink = audioLink;
    return this;
  }

   /**
   * A link to download the initial audio recording if avaliable. (Links expire 2 weeks from time of recording)
   * @return audioLink
  **/
  @ApiModelProperty(value = "A link to download the initial audio recording if avaliable. (Links expire 2 weeks from time of recording)")
  public String getAudioLink() {
    return audioLink;
  }

  public void setAudioLink(String audioLink) {
    this.audioLink = audioLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranscriptData transcriptData = (TranscriptData) o;
    return Objects.equals(this.confidence, transcriptData.confidence) &&
        Objects.equals(this.transcript, transcriptData.transcript) &&
        Objects.equals(this.emailAddress, transcriptData.emailAddress) &&
        Objects.equals(this.languageCode, transcriptData.languageCode) &&
        Objects.equals(this.sentimentType, transcriptData.sentimentType) &&
        Objects.equals(this.audioId, transcriptData.audioId) &&
        Objects.equals(this.appId, transcriptData.appId) &&
        Objects.equals(this.metadataAudio, transcriptData.metadataAudio) &&
        Objects.equals(this.unixTimeCreated, transcriptData.unixTimeCreated) &&
        Objects.equals(this.audioLink, transcriptData.audioLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confidence, transcript, emailAddress, languageCode, sentimentType, audioId, appId, metadataAudio, unixTimeCreated, audioLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranscriptData {\n");
    
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    transcript: ").append(toIndentedString(transcript)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    languageCode: ").append(toIndentedString(languageCode)).append("\n");
    sb.append("    sentimentType: ").append(toIndentedString(sentimentType)).append("\n");
    sb.append("    audioId: ").append(toIndentedString(audioId)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    metadataAudio: ").append(toIndentedString(metadataAudio)).append("\n");
    sb.append("    unixTimeCreated: ").append(toIndentedString(unixTimeCreated)).append("\n");
    sb.append("    audioLink: ").append(toIndentedString(audioLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

