/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.NSSResponse;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NSSScoreApi
 */
public class NSSScoreApiTest extends BaseTest {

    private final NSSApi api = new NSSApi();

    /**
     * Retrieve NSS Score
     *
     * Retrieve NSS Score
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insightsNssGetTest() throws ApiException {
        setup(api.getApiClient());
        Long start = null;
        Long end = null;
        String audioId = null;
        ApiResponse<NSSResponse> res = api.insightsNssGetWithHttpInfo(audioId,start, end);
        Assert.assertEquals("status", 200, res.getStatusCode());
    }
    
}
