/*
 * AimMatic API
 * APIs for Natural Voice and placeNext
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.TextDocumentResponse;
import org.junit.Assert;
import org.junit.Test;

import java.util.GregorianCalendar;

/**
 * API tests for TextDocumentApi
 */
public class TextDocumentApiTest extends BaseTest {

    private final TextApi api = new TextApi();

    /**
     * Retrieve Text
     *
     * Retrieve Text 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insightsTextGetTest() throws ApiException {
        setup(api.getApiClient());
        Long start = new GregorianCalendar(2018, 1, 1).getTimeInMillis();
        Long end = System.currentTimeMillis();
        ApiResponse<TextDocumentResponse> res = api.insightsTextGetWithHttpInfo(getAudioId(), start, end, (long)0, (long)0, "true","true");
        Assert.assertEquals("status", 200, res.getStatusCode());
        TextDocumentResponse body = res.getData();
        //res.getData().getTranscriptData().size();

    }
    
}
